server:
  port: 8080
spring:
  application:
    name: ead-api-gateway

  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri:  lb://EAD-AUTHUSER-SERVICES
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICES
          predicates:
            - Path=/ead-course/**
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
