server:
  port: 8087
application:
  prefix: AS
spring:
  profiles:
    active: development
  application:
    name: authuser-services
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: d3c0d3r
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.nom-contextual-creation: true
        properties:
          hibernate:
            show_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  output:
    ansi:
      enabled: always

logging:
  level:
    authuser: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

---
spring:
  profiles: development

---
spring:
  profiles: production