server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
application:
  prefix: CS
spring:
  profiles:
    active: development
  application:
    name: course-services
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: d3c0d3r
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.nom-contextual-creation: true
        properties:
          hibernate:
            show_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
ead:
  api:
    url:
      authuser: http://localhost:8087

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

---
spring:
  profiles: development

---
spring:
  profiles: production

